config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  devise_for :users
  get 'users/:id/profile' => 'users#profile', as: 'profile_user'
  get 'recommenders/promise' => 'recommenders#promise', as: 'promise_recommender'
  resources :users, only: [:show, :edit, :update]
  resources :recommenders, only: [:show, :new, :create]
  resources :topics, only: [:index, :create, :show, :destroy] do
    resources :recommends, only: [:new, :create, :destroy]
  end

end

app/views/layouts/shared/_flash_notice.html.erb
<% if flash[:notice] %>
  <div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert]%>
  </div>
<% end %>

app/views/layouts/shared/_post_topics.html.erb
<div class="card mb-3">
  <h3 class="card-header">投稿する</h3>
  <div class="d-flex justify-content-center align-items-center m-2">
    <%= attachment_image_tag topic, :image, :fill, 200, 200, fallback: "no_cloth.jpg", size: "200x200", id: "item_img" %>
  </div>
  <%= form_with model: topic do |f| %>
    <div class="form-group m-2">
      <label for="avatar">写真を選んでください</label><br>
      <%= f.attachment_field :image, id: "upload-img" %>
    </div>
    <br>
    <div class="form-group m-2">
      <% # 依頼したい服の傾向 %>
      <label for="exampleTextarea">服の好みや要望などを記入してください</label>
      <%= f.text_area :text, class: "form-control", id: "text", rows: "3" %>
    </div>
    <%= f.submit "投稿する", class: "btn btn-secondary pull-right m-2" %>
  <% end %>
</div>

app/views/layouts/shared/_profile.html.erb
<div class="card mb-3">
  <h3 class="card-header">
    <%= user.name %>
    <% if user.isRecommender %>
      <i class="fab fa-pied-piper-hat"></i>
    <% end %>
  </h3>
  <div class="d-flex justify-content-center align-items-center m-2">
    <%= attachment_image_tag user, :profile_image, :fill, 200, 200, fallback: "no_image.jpg", size: "200x200", style: "border-radius: 50%;", id: "profile-img" %>
  </div>
  <div class="d-flex justify-content-center align-items-center m-1">
    <div class="btn-group">
      <% unless current_page?(profile_user_path(user)) %>
        <%= link_to "プロフィールを確認", profile_user_path(user), class: "btn btn-md btn-outline-secondary", style: "text-decoration: none;"  %>
      <% end %>
      <% unless current_page?(edit_user_path(user)) %>
        <%= link_to "プロフィールを編集", edit_user_path(user), class: "btn btn-md btn-outline-secondary", style: "text-decoration: none;" %>
      <% end %>
      <% unless current_page?(user_path(user)) %>
        <%= link_to "過去の投稿をみる", user_path(user), class: "btn btn-md btn-outline-secondary", style: "text-decoration: none;" %>
      <% end %>
    </div>
  </div>
</div>