config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  devise_for :users
  get 'users/:id/profile' => 'users#profile', as: 'profile_user'
  get 'recommenders/promise' => 'recommenders#promise', as: 'promise_recommender'
  resources :users, only: [:show, :edit, :update]
  resources :recommenders, only: [:show, :new, :create]
  resources :topics, only: [:index, :create, :show, :destroy] do
    resources :recommends, only: [:new, :create, :destroy]
  end

end

app/models/topic.rb
class Topic < ApplicationRecord
  attachment :image
  belongs_to :user
  has_many :recommends, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :destroy]
  before_action :baria_topic, only: [:show]
  before_action :baria_topics, only: [:index]

  def index
    @topics = Topic.page(params[:page]).per(6).reverse_order
    @user = current_user
  end

  def show
    @recommends = @topic.recommends
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topic_path(@topic)
    else
      @user = current_user
      render 'users/show'
    end
  end

  def destroy
    @topic.destroy
    redirect_to user_path(current_user)
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :text)
  end

  def baria_topic
    topic = Topic.find(params[:id])
    unless current_user.isRecommender.present? or topic.user_id == current_user.id
      flash[:alert] = "ページ遷移できません"
      redirect_to user_path(current_user)
    end
  end

  def baria_topics
    unless current_user.isRecommender.present?
      flash[:alert] = "ページ遷移できません"
      redirect_to user_path(current_user)
    end
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/index.html.erb
<div class="container">
  <%= render "layouts/shared/flash_notice" %>
  <div class="row">
    <div class="col-lg-8">
      <div class="row">
        <% @topics.each do |topic| %>
          <div class="col-lg-6">
            <h5 class="card-header" style="background-color: white"><%= topic.user.name %>さんのリクエスト</h5>​
            <div class="card mb-4 shadow-sm">
              <div class="card-body p-0">
                <%= link_to topic_path(topic) do %>
                  <%= attachment_image_tag topic, :image, :fill, 300, 300, fallback: "no_cloth.jpg", width: "100%", height: "100%" %>
                <% end %>
                <div class="p-2">
                  <strong>服の好み・要望</strong>
                  <p class="card-text"><%= topic.text %></p>
                  <div class="d-flex justify-content-start align-items-center">
                    <div class="btn-group">
                      <%= link_to "View", topic_path(topic), class: "btn btn-sm btn-outline-secondary", style: "text-decoration: none;" %>
                    </div>
                  </div>
                  <div class="d-flex justify-content-end align-items-center">
                    <small class="text-muted"><%= topic.created_at %></small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div>
        <%= paginate @topics, class: "pagination" %>
      </div>
    </div>
    <!-- 選択した投稿の詳細 + 新しい推薦を投稿する -->
    <div class="col-lg-4">
      <%= render 'layouts/shared/profile', user: @user %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="container">
  <%= render "layouts/shared/flash_notice" %>
  <div class="row">
    <div class="col-lg-4">
      <div class="card mb-3">
        <h3 class="card-header"><%= @topic.user.name %>さんの投稿</h3>
        <div class="d-flex justify-content-center align-items-center m-2">
          <%= attachment_image_tag @topic, :image, :fill, 200, 200, fallback: "no_cloth.jpg", size: "200x200" %>
        </div>
        <div class="card-body">
          <h5>服の好み・要望</h5>
          <p class="card-text"><%= @topic.text %></p>
          <% if current_user.isRecommender and @topic.user_id != current_user.id %>
          <div class="d-flex justify-content-center align-items-center m-1">
              <div class="btn-group">
                <%= link_to "服の提案をする", new_topic_recommend_path(@topic), class: "btn btn-md btn-outline-secondary", style: "text-decoration: none;" %>
              </div>
          </div>
          <% end %>
        </div>
        <div class="card-footer d-flex justify-content-end align-items-center">
          <small class="text-muted"><%= @topic.created_at %></small>
        </div>
      </div>
    </div>
    <div class="col-lg-8">
      <h3 class="card-header" style="background-color: white;">レコメンダによる提案</h3>
      <% @recommends.each do |recommend| %>
        <div class="card text-white bg-secondary m-2" style="width: 100%; border-radius: 20px;">
        <h5 class="card-header"><%= recommend.user.name %>さんによる提案</h5>
        <div class="card-body">
          <div class="d-flex justify-content-start">
            <%= attachment_image_tag recommend, :image, :fill, 200, 200, fallback: "no_cloth.jpg", size: "200x200", class: "m-1"%>
            <div class="p-2">
              <h5 class="card-title">提案内容</h5>
              <p class="card-text">
                  <%= recommend.comment %>
              </p>
            </div>
          </div>
          <div class="d-flex justify-content-end">
            <div class="btn-group">
              <% if @topic.user == current_user %>
                <%= link_to "このレコメンダを評価する", user_path(@topic.user), class: "btn btn-outline-primary", style: "text-decoration: none;" %>
                <%= link_to "通報する", user_path(@topic.user), class: "btn btn-outline-danger ml-2", style: "text-decoration: none;" %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="card-footer d-flex justify-content-end align-items-center">
          <small class="text-muted"><%= recommend.created_at %></small>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>