config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  devise_for :users
  get 'users/:id/profile' => 'users#profile', as: 'profile_user'
  get 'recommenders/promise' => 'recommenders#promise', as: 'promise_recommender'
  resources :users, only: [:show, :edit, :update]
  resources :recommenders, only: [:show, :new, :create]
  resources :topics, only: [:index, :create, :show, :destroy] do
    resources :recommends, only: [:new, :create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  VALID_PASSWORD_REGEX =/\A(?=.*?[a-z])(?=.*?[\d])\w{6,12}\z/
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_one :recommender, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :recommends, dependent: :destroy
  validates :name, presence: true, format: { with: VALID_PASSWORD_REGEX, message: "は12文字までの半角英小文字・数字\nで構成してください。" }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:show, :edit, :update]
  before_action :set_user, only: [:show, :profile, :edit, :update]

  def show
    @topic = Topic.new
    @topics = Topic.where(user_id: current_user.id)
  end

  def profile
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :gender,
                                 :age, :height, :weight, :west, :hip, :chest, :introduction, :isRecommender)
  end

  def baria_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      flash[:alert] = "ページ遷移できません"
      redirect_to user_path(current_user)
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <%= render "layouts/shared/flash_notice" %>
  <h3 class="card-header" style="background-color: white;">プロフィールを編集</h3>​
  <div class="row">
    <!-- left column -->
    <div class="col-lg-4">
      <%= render "layouts/shared/profile", user: @user %>
    </div>
    <div class="col-lg-8 personal-info">
      <%= form_with model: @user do |f| %>
        <label for="avatar">写真を選んでください</label><br>
        <%= f.file_field :profile_image, id: "upload-profile" %>
        <div class="form-group">
          <%= f.label :name, class: "col-form-label", for: "name" %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "name", id: "name" %>
        </div>
        <div class="form-group">
          <label for="gender">性別</label><br>
          <%= f.select :gender, {'未選択': '未選択', '男性': '男性', '女性': '女性', '未公開': '未公開'}, {}, {class: 'form-control', id: 'gender'} %>
        </div>
        <div class="form-group">
          <label for="age">年齢 [歳]</label><br>
          <%= f.select :age, {'未選択': '未選択', '~17': '~17', '18~': '18~', '20~': '20~', '25~': '25~', '30~': '30~', '35~': '35~', '40~': '40~', '45~': '45~', '50~': '50~', '55~': '55~', '60~': '60~', '未公開':'未公開'}, {}, {class: 'form-control', id: 'age'} %>
        </div>
        <div class="form-group">
          <label for="height">身長 [cm]</label><br>
          <%= f.select :height, {'未選択': '未選択', '~139': '~139', '140~': '140~', '150~': '150~', '160~': '160~', '170~': '170~', '180~': '180~', '190~': '190~', '200~': '200~', '未公開': '未公開'}, {}, {class: 'form-control', id: 'height'} %>
        </div>
        <div class="form-group">
          <label for="weight">体重 [kg]</label><br>
          <%= f.select :weight, {'未選択': '未選択', '~39': '~39', '40~': '40~', '50~': '50~', '60~': '60~', '70~': '70~', '80~': '80~', '90~': '90~', '未公開': '未公開'}, {}, {class: 'form-control', id: 'weight'} %>
        </div>
        <div class="form-group">
          <%= f.label :west, class: "col-form-label", for: "west" %>
          <%= f.text_field :west, autofocus: true, autocomplete: "west", class: "form-control", placeholder: "west", id: "west" %>
        </div>
        <div class="form-group">
          <%= f.label :hip, class: "col-form-label", for: "hip" %>
          <%= f.text_field :hip, autofocus: true, autocomplete: "hip", class: "form-control", placeholder: "hip", id: "hip" %>
        </div>
        <div class="form-group">
          <%= f.label :chest, class: "col-form-label", for: "chest" %>
          <%= f.text_field :chest, autofocus: true, autocomplete: "chest", class: "form-control", placeholder: "chest", id: "chest" %>
        </div>
        <div class="form-group">
          <% # introduction: 自己紹介プロフィール %>
          <label for="exampleTextarea">自己紹介</label>
          <%= f.text_area :introduction, class: "form-control", id: "introduction", rows: "3" %>
        </div>
        <%= f.submit "Update user profile", class: "btn btn-outline-secondary mb-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container">
  <h3 class="card-header" style="background-color: white;">プロフィール</h3>​
  <div class="row">
    <!-- left column -->
    <div class="col-lg-4">
      <%= render 'layouts/shared/profile', user: @user %>
    </div>
    <!-- display profile data -->
    <div class="col-lg-8 personal-info">
      <form class="form-horizontal" role="form">
        <div class="form-group">
          <label class="col-lg-3 control-label">NameID:</label>
          <%= @user.name %>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">メールアドレス:</label>
          <%= @user.email %>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">年齢:</label>
          <%= @user.age %>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">性別:</label>
          <%= @user.gender %>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">身長:</label>
          <%= @user.height %>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">体重:</label>
          <%= @user.weight %>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">チェスト:</label>
          <%= @user.chest %>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">ウエスト:</label>
          <%= @user.west %>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">ヒップ:</label>
          <%= @user.hip %>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">イントロダクション:</label>
          <%= @user.introduction %>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/users/roles.html.erb
<div class="container">
  ​<%= render "devise/shared/error_messages", resource: @user %>
  <div class="row">
    <div class="col-md-10 m-auto">
      <h3 class="card-header" style="background-color: white;">レコメンダ登録</h3>​
      <div class="m-auto w-75">
        <h4>誓約書</h4>
        <iframe src="https://frs-bucket.s3.amazonaws.com/contract.pdf"
                width="100%" height="1000px"></iframe>
        <br>
        <div class="m-auto">
          <div class="d-flex justify-content-center align-items-center m-2 w-100">
            <button id="check-button" type="button" class="btn btn-primary btn-lg">誓約書に同意する</button>
          </div>
          <br>
          <div id="recommender-form" style="display: none;">
            <%= form_with model: @user do |f| %>
              <h4>個人情報を入力してください</h4>
              <div class="form-group">
                <label>本名</label>
                <%= f.text_field :real_name, autofocus: true, autocomplete: "real_name", class: "form-control", placeholder: "本名" %>
              </div>
              <div class="form-group">
                <label>住所</label>
                <%= f.text_field :address, autofocus: true, autocomplete: "address", class: "form-control", placeholder: "住所" %>
              </div>
              <div class="form-group">
                <label>電話番号</label>
                <%= f.number_field :phone_number, autofocus: true, autocomplete: "phone_number", class: "form-control", placeholder: "電話番号" %>
              </div>
              <br>
              <div class="d-flex justify-content-end align-items-center mb-3">
                <%= f.submit "レコメンダ登録", class: 'btn btn-secondary' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= render "layouts/shared/flash_notice" %>
  <div class="row">
    <div class="col-lg-8">
      <h3 class="card-header" style="background-color: white;">過去の投稿</h3>​
      <div class="row">
        <% @topics.reverse_each do |topic| %>
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <div class="card-body p-0">
                <%= link_to topic_path(topic) do %>
                  <%= attachment_image_tag topic, :image, :fill, 300, 300, fallback: "no_cloth.jpg", width: "100%", height: "100%" %>
                <% end %>
                <div class="p-2">
                  <strong>服の好み・要望</strong>
                  <p class="card-text"><%= topic.text %></p>
                  <div class="d-flex justify-content-start align-items-center">
                    <div class="btn-group">
                      <%= link_to "View", topic_path(topic), class: "btn btn-sm btn-outline-secondary", style: "text-decoration: none;" %>
                      <%= link_to "Delete", topic_path(topic), class: "btn btn-sm btn-outline-secondary", method: :delete, style: "text-decoration: none;" %>
                    </div>
                  </div>
                  <div class="d-flex justify-content-end align-items-center">
                    <small class="text-muted"><%= topic.created_at %></small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4">
      <%= render 'layouts/shared/profile', user: @user %>
      <% if @user.id == current_user.id %>
        <%= render 'layouts/shared/post_topics', topic: @topic %>
      <% end %>
    </div>
  </div>
</div>