config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  devise_for :users
  get 'users/:id/profile' => 'users#profile', as: 'profile_user'
  get 'recommenders/promise' => 'recommenders#promise', as: 'promise_recommender'
  resources :users, only: [:show, :edit, :update]
  resources :recommenders, only: [:show, :new, :create]
  resources :topics, only: [:index, :create, :show, :destroy] do
    resources :recommends, only: [:new, :create, :destroy]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>FaReS</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>
  <% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "Fashion Recommender's", user_path(current_user), class: "navbar-brand" %>
      <div class="pull-right">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "ホーム", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "プロフィール", profile_user_path(current_user), class: "nav-link" %>
          </li>
          <% if current_user.isRecommender %>
            <li class="nav-item">
              <%= link_to "トピックス", topics_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">レコメンダ</a>
            <div class="dropdown-menu">
              <% if not current_user.isRecommender %>
                <%= link_to "レコメンダになる", new_recommender_path(current_user), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
              <% end %>
              <%= link_to "※レコメンダ誓約書", promise_recommender_path, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "サインアウト", destroy_user_session_path, class: "nav-link", method: :delete %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <% end %>
</header>

<main>
  <%= yield %>
</main>
</body>
</html>